name: Form-engine-CI

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'
  release:
    types:
      - created

env:
  ESM_NAME: "openmrs-ohri-form-engine-lib"
  JS_NAME: "openmrs-ohri-form-engine-lib.js"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      - run: yarn install
      - run: yarn lint
      - run: yarn run test
      - run: yarn build
      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: dist
          path: |
            dist

  pre_release:
    runs-on: ubuntu-latest

    needs: build

    if: ${{ github.ref == 'refs/heads/main' && github.event_name == 'push' }}

    steps:
      - uses: actions/checkout@v3

      - name: Download Artifacts
        uses: actions/download-artifact@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          registry-url: "https://registry.npmjs.org"
      - run: yarn install
      - run: sed -i -e "s/\(\"version\":\\s\+\"\([0-9]\+\.\?\)\+\)/\1-pre.${{ github.run_number }}/" 'package.json'
      - run: |
         yarn config set npmAlwaysAuth true
         yarn config set npmAuthToken ${{ secrets.NPM_OHRI_ACCESS_TOKEN }}
      - run: yarn npm publish --tag next

  release:
    runs-on: ubuntu-latest

    needs: build

    if: ${{ github.event_name == 'release' }}

    steps:
      - uses: actions/checkout@v3
      - name: Download Artifacts
        uses: actions/download-artifact@v3
      - name: Use Node.js
      # Setup .npmrc file to publish to npm
        uses: actions/setup-node@v3
        with:
          node-version: "16.x"
          registry-url: "https://registry.npmjs.org"
      - run: npm ci
      - run: npm publish --tag latest
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_OHRI_ACCESS_TOKEN }}
          
  bump-form-engine:
    runs-on: ubuntu-latest

    needs: release
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          repository: UCSF-IGHS/openmrs-esm-ohri
          ref: working
      
      - name: Install dependencies
        run: yarn

      - name: Bump form engine
        run: yarn ci:bump-form-engine

      - name: Commit changes
        run: |
          git config user.email "github-actions@github.com"
          git config user.name "GitHub Actions"
          git add yarn.lock
          git commit -m "(chore) bump-form-engine"

      - name: Create PR
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "(chore) bump-form-engine"
          title: "(chore) Bump form engine"
          body: "This PR bumps the form engine, based on the latest change from the form-engine-repo"
          branch: bump-form-engine
          base: working
